### ISSUE TITLE
Docker installation method?

### ISSUE THREAD

**Issue by ll3N1GmAll** [fkie-cad/bountyhunter#5]
Thanks for releasing this. It looks great. Can't wait to get in and start playing with it! :D 

How can this plugin be installed in a Docker Caldera installation? Attempting to follow the instructions fails once I get to the pip install requirements portion because there are dependency conflicts on my system. This is why I am running the docker version of Caldera. So, how can I install and configure the bountyhunter plugin within a docker deployment of Caldera?

**Comment by L015H4CK** [comment]
Thanks for checking out the project!

I added a short [docker installation guide](https://github.com/fkie-cad/bountyhunter/tree/update-readme?tab=readme-ov-file#docker-installation-guide) to the README. Let me know if this works out for you or if you run into any problems.

In the past, I have found that the docker version of Caldera is not easy to use and configure, e.g., I find editing the server's or a planner's config file very tedious compared to a non-docker installation. Have you tried installing and running the Caldera server in a [python venv](https://docs.python.org/3/library/venv.html)? This should fix any dependency conflicts unless they are directly related to Caldera.

**Comment by ll3N1GmAll** [comment]
Thanks for this! I will follow your instructions and report back with my results. Will also look into doing this in a venv as an alternative to docker (which i would prefer as I do not much care for docker unless it is absolutely necessary).

**Comment by ll3N1GmAll** [comment]
Is it ok to just add the following lines at the very bottom of the Dockerfile under the entry point?
WORKDIR /usr/src/app/plugins/bountyhunter
RUN pip3 install -r requirements.txt

**Comment by L015H4CK** [comment]
Sorry, the guide was not detailed enough. Try adding the two lines at line 77, this should fix the issue. Let me know if this works.

**Comment by ll3N1GmAll** [comment]
No trouble at all. I appreciate your efforts and assistance! To make sure I'm on the correct line, should I add it right before the following? 

WORKDIR /usr/src/app

# Install Node.js, npm, and other build VueJS front-end

**Comment by L015H4CK** [comment]
Yes, that should work. I will check my test installation shortly to confirm.

**Comment by ll3N1GmAll** [comment]
That did solve the build fail issue. Will test out the plugin to verify functionality and report back.

**Comment by L015H4CK** [comment]
Issue resolved with https://github.com/fkie-cad/bountyhunter/pull/7.

Thanks for your input and help improving the project for others @ll3N1GmAll!

If you run into further problems, please open a new issue!
